name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configura o Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: laura-stov
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz o deploy no branch `output`
      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
